  export const WALKING_ESTIMATED_CALAROIED_PER_STEPS = 0.03218;
  export const RUNNING_ESTIMATED_CALAROIED_PER_STEPS = 0.06391;
  export const CYCLING_ESTIMATED_CALAROIED_PER_STEPS = 0.08;
  export const SWIMMING_ESTIMATED_CALAROIED_PER_STEPS = 0.1;