import {
  CYCLING_ESTIMATED_CALAROIED_PER_STEPS,
  RUNNING_ESTIMATED_CALAROIED_PER_STEPS,
  SWIMMING_ESTIMATED_CALAROIED_PER_STEPS,
  WALKING_ESTIMATED_CALAROIED_PER_STEPS,
} from "../constants/estimatedCalories";

export const activitiesCalMapper = {
  "Walking": WALKING_ESTIMATED_CALAROIED_PER_STEPS,
  "Running": RUNNING_ESTIMATED_CALAROIED_PER_STEPS,
  "Cycling": CYCLING_ESTIMATED_CALAROIED_PER_STEPS,
  "Swimming": SWIMMING_ESTIMATED_CALAROIED_PER_STEPS,
};
